before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq odbc-postgresql unixodbc-dev

script: hostname; cat /etc/hosts; ifconfig; sudo service postgresql stop; cd iRODS; ./irodssetup < ../.travis.irodssetup.input; yes | ./irodsctl devtest
