before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq odbc-postgresql unixodbc-dev

script: hostname; cat /etc/hosts; ifconfig; sudo service postgresql stop; cd iRODS; export USE_LOCALHOST=1; ./irodssetup < ../.travis.irodssetup.input; cat /home/travis/build/irods/irods/iRODS/installLogs/finishSetup.log; cat /home/travis/build/irods/irods/iRODS/server/log/rodsLog*; cat ~/.irods/.irodsEnv; set +e; yes | ./irodsctl devtest; DEVTESTSTATUS=$?; if [ "$DEVTESTSTATUS" != "0" ] ; then cat /tmp/testSurvey_*; cat /tmp/icatSurvey_*; cat /home/travis/build/irods/irods/iRODS/server/test/bin/*; exit 1; fi;
